Sprint_2
drzoiberg2005/middle.messenger.praktikum.yandex pull request #4
Opened 2022-02-05 04:50 UTC by drzoiberg2005

Добрый день! Проверьте пожалуйста выполнение задания второго спринта и можете не стесняться в выражениях, говорите как есть, хочу научиться как правильно)))

2022-02-05 11:10 UTC, DmitryKhitrin requested changes
Привет, спасибо за вашу работу - выглядит просто супер) В комментариях я постарался сформулировать несколько вопросов и предложений, посмотрите на них пожалуйста.

Из того что точно хотелось бы поправить:

- описание типов для props;
- избавить от дублирования подходов работы с сетью;

2022-02-05 11:10 UTC, khitrind commented on .stylelintrc.json
> +}
Для git важно, что бы файл заканчивался [пустой строкой](https://stackoverflow.com/questions/5813311/whats-the-significance-of-the-no-newline-at-end-of-file-log)

2022-02-05 11:10 UTC, khitrind commented on netlify.toml
> +
[EOF](https://eslint.org/docs/rules/eol-last)

2022-02-05 11:10 UTC, khitrind commented on src/components/form/index.ts
> +        events: any;
Event

2022-02-05 11:10 UTC, khitrind commented on src/components/header/index.ts
> +    super("div", { ...props, button, title: props.page });
Гораздо нагляднее получается не спредить пропсы, а явно передавать аргументы, в будщем будет гораздо легче разобраться, что откуда прилетело)

2022-02-05 11:10 UTC, khitrind commented on src/components/header/index.ts
> +    const avatar = generateavatar(user, 6).outerHTML;
В мире веба переменные принято именовать в [camelCase](https://techrocks.ru/2018/08/09/most-common-programming-case-types/). Таким образом, тут получится `generateAvatar`

2022-02-05 11:10 UTC, khitrind commented on src/components/header/index.ts
> +      class: "header__user",
В рамках кнопки, класс может значит очень много всего, так что в данном случае было бы уместней назвать параметр className, коим он и является

2022-02-05 11:10 UTC, khitrind commented on src/constants/inputs.ts
> +    value: user ? user.login : "",
Зачем тут проверка, если юзер это константа?

2022-02-05 11:10 UTC, khitrind commented on src/layout/block/index.ts
> +abstract class Block {
props лучше типизировать через [generics](https://www.typescriptlang.org/docs/handbook/2/generics.html)], так будет возможность точно передать в базовый блок, тип пропсов наследников.

В общем виде должно получиться, что-то такое:

```
abstract class Block<Props extends {}> {
    private element: HTMLElement;
    private tagName: string;

    protected props: Props;

    public constructor(tagName: string = 'div', propsAndChildren: Props) {
        this.tagName = tagName;
        this.props = propsAndChildren;
    }
}

type ButtonProps = {
    onClick: () => {};
};

class Button extends Block<ButtonProps> {
    public constructor(props: ButtonProps) {
        super('div', props);
    }

    public onClick() {
        this.props.onClick();
    }
}


```

2022-02-05 11:10 UTC, khitrind commented on src/layout/indexOld.ts
> +export default class {
Анонимные классы - это что-то новенькое) Расскажете, почему было принято решение сделать именно так?

2022-02-05 11:10 UTC, khitrind commented on src/layout/indexOld.ts
> +  updateLayout = async (type: any) => {
зачем тут async? Async нужен, если внутр функции используется await, в остальном - это просто функция возвращающая Promise

2022-02-05 11:10 UTC, khitrind commented on src/pages/500/404.tmpl copy.ts
> +            <span class="simple__page-content-item-subtitle">ЧТО-ТО ПОШЛО НЕ ТАК</span>
Хорошая практика выносить текст из компонентов в переменные, таким образом верстка становится более универсальной + проще решаются вопросы локализации к примеру)

2022-02-05 11:10 UTC, DmitryKhitrin commented on src/pages/profile/index.ts
> +    let title = user.display_name;
Тут кажется излишнем выносить это в переменную, так как на сколько я вижу эта переменная используется всего в одном месте

2022-02-05 11:10 UTC, DmitryKhitrin commented on src/utils/HTTPTransport.ts
> +        isGet && data ? `${url}${this.queryStringify(data)}` : url
query параметры можно передавать не только для метода get. Тут два варианта решения этой проблемы) Либо формировать url внутри методов get, post... Либо принимать в options два параметра:

- params - их мы перекладываем в query
- data - это поле передаем в body запроса (это поле мы не передаем из метода get)

2022-02-05 11:10 UTC, DmitryKhitrin commented on src/utils/generateavatar.ts
> +    if (object.avatar && object.avatar !== null) {
А зачем так сложно, поему не возможности объявить аватар так же в шаблоне?

2022-02-05 11:10 UTC, DmitryKhitrin commented on src/utils/http.ts
> +const fetch = async (
Тут тоже интересный вопрос, зачем вам и fetch и HTTPTransport, они же по сути выполняют одну и ту же задачу?

2022-02-05 11:10 UTC, DmitryKhitrin commented on src/utils/validation.ts
> +      pattern: /.+@[^@]+[a-z]+\.[^@]{2,}$/,
Это регулярные выражение не очень подходит для валидации email, так как не учитывает огромное количество кейсов:

`/.+@[^@]+[a-z]+\.[^@]{2,}$/.test("asdsa@asdasd.ru...sdassadas.")`

Люди годами валидировали почту, так что не стоит пренебрегать опытом [предков](https://emailregex.com/)) Главное в это деле, не забыть оставить ссылку на источник)

2022-02-05 11:10 UTC, DmitryKhitrin commented on static/consts.ts
> +export let messages = [
```suggestion
export const messages = [
```
Ни на что технически не влияет, кроме ощущения безопасности)

2022-02-05 13:01 UTC, drzoiberg2005 commented on static/consts.ts
> +export let messages = [
Поправил

2022-02-05 13:02 UTC, drzoiberg2005 commented on src/utils/validation.ts
> +      pattern: /.+@[^@]+[a-z]+\.[^@]{2,}$/,
Спасибо большое, я все искал, где найти шаблоны для нормальной валидации всего и вся)))

2022-02-05 13:02 UTC, drzoiberg2005 commented on src/utils/http.ts
> +const fetch = async (
fetch я реализовал в рамках первого спринта самостоятельно, во втором сделал HTTPTransport по учебным материалам. Поправил и удалил fetch

2022-02-05 13:05 UTC, drzoiberg2005 commented on src/constants/inputs.ts
> +    value: user ? user.login : "",
В рамках первого спринта был реализован запрос к бэку и во избежание ошибок в виде вывода в инпуте undefined, добавил проверку. В этом спринте на все доработки времени физически не хватало.

2022-02-05 13:10 UTC, drzoiberg2005 commented on src/components/header/index.ts
> +    const avatar = generateavatar(user, 6).outerHTML;
Да это я протупил, в основном пытался использовать camelCase

2022-02-05 13:28 UTC, drzoiberg2005 commented on src/layout/indexOld.ts
> +export default class {
В этом спринте я практически все переписывал заново, с целью устранить связанность. Это код с первого спринта с окончанием Old в названии, забыл удалить))) Я не в курсе, что анонимные классы не используют, до этого учился самостоятельно по youtube и статьям в интернете, так что вполне могу писать что-то напоминающее ахинею)) Поэтому и не устраиваюсь работать программистом, так как люди годами специально для этого учатся, а я работаю юристом и когда было скучно увлекся программированием и что бы не позориться говнокодом потихоньку учусь))) так что пиши если что-то не так

2022-02-05 13:29 UTC, drzoiberg2005 commented on src/layout/indexOld.ts
> +  updateLayout = async (type: any) => {
Коммент выше^

2022-02-05 14:10 UTC, drzoiberg2005 commented on src/components/form/index.ts
> +        events: any;
Исправил

2022-02-05 14:11 UTC, drzoiberg2005 commented on netlify.toml
> +
Добавил правило

2022-02-05 14:11 UTC, drzoiberg2005 commented on .stylelintrc.json
> +}
Исправил

2022-02-05 14:20 UTC, drzoiberg2005 commented on src/components/header/index.ts
> +      class: "header__user",
Исправил, в итоге все очень становиться похожим на реакт

2022-02-05 22:12 UTC, drzoiberg2005 commented on src/utils/generateavatar.ts
> +    if (object.avatar && object.avatar !== null) {
Исправил

2022-02-06 00:53 UTC, drzoiberg2005 commented on src/components/header/index.ts
> +    super("div", { ...props, button, title: props.page });
Исправил

2022-02-06 07:58 UTC, drzoiberg2005 commented on src/layout/block/index.ts
> +abstract class Block {
Добавил generics

2022-02-06 08:02 UTC, drzoiberg2005 commented on src/pages/500/404.tmpl copy.ts
> +            <span class="simple__page-content-item-subtitle">ЧТО-ТО ПОШЛО НЕ ТАК</span>
Исправил

2022-02-06 08:08 UTC, drzoiberg2005 commented on src/utils/HTTPTransport.ts
> +        isGet && data ? `${url}${this.queryStringify(data)}` : url
Исправил на два параметра

2022-02-06 08:51 UTC, drzoiberg2005 commented
Добрый день, Дмитрий! Спасибо большое за подробное ревью. Сам я работаю юристом, а программирование до курса изучал самостоятельно по видео из youtube и google, так что вполне вероятно где-нибудь пишу ахинею, так что все замечания для меня важны и можешь не стесняться в выражениях))).

2022-02-06 15:55 UTC, DmitryKhitrin commented on src/layout/indexOld.ts
> +export default class {
Нее, я к тому, что обычно у переменных есть имена, а тут просто класс без имени, вот и удивлся)

2022-02-06 15:57 UTC, DmitryKhitrin approved these changes
Спасибо большое за правки, теперь работа выглядит гораздо чище!)

На самом деле не важно кем вы работали до этого, главное - это что вам интересно. 
А работа получилась отличной, удачи в следующем спринте!)

2022-02-07 15:42 UTC, merged